POST http://localhost:8081/api/v1/
Content-Type: application/json

{
  "email":"al@gmail.com",
  "password": "Test12345-"
}


###

GET http://localhost:8081/api/v1/users
###
GET http://localhost:8082/api/v1/diceValue

###
GET http://localhost:8081/api/v1/get_chat_messages
###
GET http://localhost:8081/api/v1/get_all_messages